### ISSUE TITLE
enroll secure boot key? 

### ISSUE THREAD

**Issue by orcbolg3612** [john-ghatas/silverblue-setup#1]
host@fedora:~$ just enroll-secure-boot-key
bash: just: command not found
host@fedora:~$ 

What should i do?

**Comment by john-ghatas** [comment]
Are you running the ublue image? It's mentioned as the first thing that you need to do.

![image](https://github.com/john-ghatas/silverblue-setup/assets/14125058/6aa89918-6e0d-4e2f-b0ba-e78824455908)

https://universal-blue.org/images/, please read carefully through the instructions.
